import yfinance as yf
ticker_symbol = 'TSLA'
tesla_data = yf.download(ticker_symbol, start='2023-04-06', end='2024-04-06')
print(tesla_data)


import requests
from bs4 import BeautifulSoup

# Send an HTTP request to the webpage
url = 'https://example.com/tesla-revenue'
response = requests.get(url)

# Parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Find the HTML element containing the revenue data
revenue_element = soup.find('div', class_='revenue')

# Extract the revenue data
tesla_revenue = revenue_element.text.strip()

print('Tesla Revenue:', tesla_revenue)
